name: Build

on:
  push:
    branches: [ master ]
    paths:
      - minecraft-server/**
      - versions
  workflow_dispatch:
  workflow_call:

jobs:

  build_arm64:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Enable multiarch bulid
      run: sudo podman run --rm --privileged docker.io/tonistiigi/binfmt --install all
    
    - name: Build arm64 container
      run: ./build.sh -r ghcr.io/${{ github.repository }} -t latest-arm64 -a arm64
    
    - name: Container Registry Login
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ github.actor }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      run: podman push ghcr.io/${{ github.repository }}:latest-arm64

  build_amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Build amd64 container
      run: ./build.sh -r ghcr.io/${{ github.repository }} -t latest-amd64
    
    - name: Container Registry Login
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ github.actor }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      run: podman push ghcr.io/${{ github.repository }}:latest-amd64

  manifest:
    runs-on: ubuntu-latest
    needs:
    - build_arm64
    - build_amd64
    steps:

    - name: Container Registry Login
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ github.actor }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create manifest
      run: |
        podman manifest create \
          ghcr.io/${{ github.repository }}:latest \
          docker://ghcr.io/${{ github.repository }}:latest-amd64 \
          docker://ghcr.io/${{ github.repository }}:latest-arm64

    - name: Push images
      run: podman manifest push ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:latest
