name: Update
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:

  update:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.push.outputs.updated }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Update versions in file
      run: ./update.sh
    
    - name: Push changes
      id: push
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add -A
          git commit -m 'Versions updated' --allow-empty
          git push
          echo "::set-output name=updated::yes"
        else
          echo "::set-output name=updated::no"
        fi
  
  build:
    needs: update
    if: needs.update.outputs.updated == 'yes'
    uses: ./.github/workflows/build.yml