name: Update
on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:

  update:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    
    - name: Update versions in file
      run: ./update.sh
    
    - name: Push changes
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name '${{ github.actor }} Actions'
          git config --global user.email '${{ github.actor }}-actions@users.noreply.github.com'
          git add -A
          git commit -m 'Versions updated' --allow-empty
          git push
        fi
  
